_target_: opr.losses.MultimodalTripletMarginLoss

margin: 0.2
swap: True
distance:
  _target_: pytorch_metric_learning.distances.LpDistance
  normalize_embeddings: False
  collect_stats: True
miner:
  _target_: opr.miners.HardTripletMiner
  distance:
    _target_: pytorch_metric_learning.distances.LpDistance
    normalize_embeddings: False
reducer:
  _target_: pytorch_metric_learning.reducers.AvgNonZeroReducer
  collect_stats: True
modalities: [image, cloud, fusion]
weights: [0.5, 0.5, 0.]
