staff_classes:
  - wall
  - building
  - sky
  - floor
  - tree
  - ceiling
  - road
  - bed
  - window
  - grass
  - cabinet
  - sidewalk
  - person
  - earth
  - door
  - table
  - mountain
  - plant
  - curtain
  - chair
  - car
  - water
  - painting
  - sofa
  - shelf
  - house
  - sea
  - mirror
  - rug
  - field
  - armchair
  - seat
  - fence
  - desk
  - rock
  - wardrobe
  - lamp
  - bathtub
  - railing
  - cushion
  - base
  - box
  - column
  - signboard
  - chest
  - counter
  - sand
  - sink
  - skyscraper
  - fireplace
  - refrigerator
  - grandstand
  - path
  - stairs
  - runway
  - case
  - pool
  - pillow
  - screen
  - stairway
  - river
  - bridge
  - bookcase
  - blind_screen
  - coffee
  - toilet
  - flower
  - book
  - hill
  - bench
  - countertop
  - stove
  - palm
  - kitchen_island
  - computer
  - swivel_chair
  - boat
  - bar
  - arcade_machine
  - hovel
  - bus
  - towel
  - light_source
  - truck
  - tower
  - chandelier
  - sunshade
  - streetlight
  - booth
  - television
  - airplane
  - dirt
  - apparel
  - pole
  - land
  - balustrade
  - escalator
  - ottoman
  - bottle
  - buffet
  - poster
  - stage
  - van
  - ship
  - fountain
  - conveyer
  - canopy
  - washer
  - toy
  - swimming_pool
  - stool
  - barrel
  - basket
  - waterfall
  - tent
  - bag
  - minibike
  - cradle
  - oven
  - ball
  - food
  - step
  - tank
  - trade
  - microwave
  - pot
  - animal
  - bicycle
  - lake
  - dishwasher
  - projection_screen
  - blanket
  - sculpture
  - hood
  - sconce
  - vase
  - traffic_light
  - tray
  - ashcan
  - fan
  - pier
  - crt_screen
  - plate
  - monitor
  - bulletin_board
  - shower
  - radiator
  - glass
  - clock
  - flag

special_classes:
  - tree
  - bed
  - window
  - cabinet
  - door
  - table
  - plant
  - chair
  - water
  - painting
  - sofa
  - shelf
  - mirror
  - rug
  - armchair
  - seat
  - desk
  - lamp
  - bathtub
  - railing
  - cushion
  - column
  - signboard
  - chest
  - counter
  - sink
  - fireplace
  - refrigerator
  - grandstand
  - stairs
  - pillow
  - screen
  - stairway
  - bookcase
  - blind_screen
  - coffee
  - toilet
  - flower
  - bench
  - countertop
  - kitchen_island
  - computer
  - swivel_chair
  - bar
  - arcade_machine
  - booth
  - television
  - pole
  - balustrade
  - escalator
  - ottoman
  - buffet
  - poster
  - stage
  - basket
  - cradle
  - step
  - trade
  - microwave
  - dishwasher
  - projection_screen
  - sculpture
  - sconce
  - vase
  - ashcan
  - fan
  - crt_screen
  - monitor
  - bulletin_board
  - shower
  - radiator
  - clock
  - flag

num_special: 73
num_classes: 150