dataset:
  _target_: opr.datasets.custom.PhystechCampus

  dataset_root: /home/docker_opr/Datasets/MIPT_Campus_preprocessed/splitted/train
  modalities: [image, cloud,]
  images_subdir: front_cam
  mink_quantization_size: 0.01

sampler:
  _target_: opr.datasets.samplers.batch_sampler.BatchSampler

  batch_size: 16
  batch_size_limit: null
  batch_expansion_rate: null
  positives_per_group: 2
  seed: 3121999

num_workers: 4
